### ISSUE TITLE
httpbin fails with werkzeug 2.1.0

### ISSUE THREAD

**Issue by xqt** [kevin1024/pytest-httpbin#72]
httpbin fails with werkzeug 2.1.0 but httpbin is not maintained for 4 years. Consider to find another solution to replace httpbin or take over the httpbin code parts.
See https://github.com/postmanlabs/httpbin/issues/673

**Comment by mgorny** [comment]
Could you add a dependency on `werkzeug<2.1` directly to pytest-httpbin for the time being and make a new release with that?

Currently installing pytest-httpbin doesn't work out of the box because it pulls in httpbin and werkzeug versions that aren't compatible with each other. Until httpbin is forked and reclaimed properly, pytest-httpbin seems the best place to workaround the problem.

The alternative is adding `werkzeug<2.1` deps in packages using pytest-httpbin, and that's simply going to suck long-term because then we'd have to fix them all over the place once a fixed version of httpbin is released.

**Comment by kevin1024** [comment]
as an update, we have forked httpbin, so hopefully we will have a fix for this soon.

**Comment by mgorny** [comment]
Gentle ping. How do we proceed from here? Do you need someone to repost the pull requests from the original httpbin repo to the fork?

**Comment by kevin1024** [comment]
Yes please! That would be very helpful.

**Comment by kevin1024** [comment]
OK, I have pushed a new release of httpbin (0.10.0) with the fixes from the fork to pypi.
